<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#import" data-toc-modified-id="import-1">import</a></span></li><li><span><a href="#함수-체크" data-toc-modified-id="함수-체크-2">함수 체크</a></span><ul class="toc-item"><li><span><a href="#get_lexicon()" data-toc-modified-id="get_lexicon()-2.1">get_lexicon()</a></span></li><li><span><a href="#get_tfidf_from_konlpy()" data-toc-modified-id="get_tfidf_from_konlpy()-2.2">get_tfidf_from_konlpy()</a></span></li><li><span><a href="#get_tfidf_from_nltk()" data-toc-modified-id="get_tfidf_from_nltk()-2.3">get_tfidf_from_nltk()</a></span></li><li><span><a href="#Extend-Lexicon" data-toc-modified-id="Extend-Lexicon-2.4">Extend Lexicon</a></span></li></ul></li><li><span><a href="#inverted-index-with-tf" data-toc-modified-id="inverted-index-with-tf-3">inverted index with tf</a></span></li><li><span><a href="#dtm-tdm-twm" data-toc-modified-id="dtm-tdm-twm-4">dtm-tdm-twm</a></span></li><li><span><a href="#evaluate-idf" data-toc-modified-id="evaluate-idf-5">evaluate idf</a></span></li><li><span><a href="#numpy를-활용한-info_retrieval.py-성능-개선" data-toc-modified-id="numpy를-활용한-info_retrieval.py-성능-개선-6">numpy를 활용한 info_retrieval.py 성능 개선</a></span><ul class="toc-item"><li><span><a href="#tf,-idf" data-toc-modified-id="tf,-idf-6.1">tf, idf</a></span></li><li><span><a href="#collection,-clean_collection" data-toc-modified-id="collection,-clean_collection-6.2">collection, clean_collection</a></span></li><li><span><a href="#tf-idf-..." data-toc-modified-id="tf-idf-...-6.3">tf-idf ...</a></span></li></ul></li></ul></div>

## import

In [1]:
import os
import sys
sys.path.append(os.path.abspath(os.path.join('..')))

In [2]:
from functions.info_retrieval import get_lexicon
from functions.info_retrieval import get_tfidf_from_konlpy
from functions.info_retrieval import get_tfidf_from_nltk
from functions.info_retrieval import clean_collection
from functions.info_retrieval import extend_lexicon
from functions.info_retrieval import inverted_index_with_tf
from functions.info_retrieval import get_tdm_from_dtm
from functions.info_retrieval import tdm2twm
from functions.info_retrieval import evaluate_idf

In [32]:
from konlpy.corpus import kolaw
from konlpy.tag import Okt
from nltk.corpus import brown
from nltk.tokenize import word_tokenize

In [4]:
import numpy as np
import pandas as pd

## 함수 체크

### get_lexicon()

In [5]:
kobill_lexicon = get_lexicon()

In [6]:
kobill_lexicon[:100]

array(['행정절차법', '일부개정법률안', '(유선호의원', '대표발의', ')', '의', '안', '번', '호',
       '9896', '발의연월일', ':', '2010.', '11.', '15.', '발', '의', '자', ':',
       '유선호․강기갑․김효석', '최문순ㆍ최재성ㆍ조영택', '김성곤ㆍ문학진ㆍ백재현', '송민순ㆍ양승조ㆍ신낙균',
       '조배숙ㆍ박은수ㆍ정동영', '김춘진ㆍ김재윤ㆍ우윤근', '이성남ㆍ박영선', '의원', '(20인)', '제안이유',
       '현행법은', '입법예고와', '행정예고를', '통하여', '정책', '결정', '과정에', '국민', '참',
       '여의', '절차를', '규정하고', '있기는', '하나', '실제', '정책', '결정·집행·평가의', '단계',
       '에서', '근본적인', '국민', '참여', '규정은', '거의', '없어', '위임입법에', '의하여', '정책',
       '결정', '및', '집행', '권한이', '부여되는', '문제점이', '있음.', '따라서', '입법예고',
       '이전의', '국민적', '협의절차와', '재입법예고', '규정', '등을', '신설하고,', '당사자', '등의',
       '개념을', '명확히', '하여', '당사자의', '신청에', '의한', '청', '문의', '기회를', '보장하는',
       '한편,', '법령상의', '일부', '미비점을', '개선․보완함으', '-', '1', '-', '-', '2',
       '-', '로써', '실질적인', '국민', '참여의'], dtype='<U32')

In [7]:
kolaw_lexicon = get_lexicon(corpus=kolaw)

In [8]:
kolaw_lexicon[:100]

array(['대한민국헌법', '유구한', '역사와', '전통에', '빛나는', '우리', '대한국민은', '3·1운동으로',
       '건립된', '대한민국임시정부의', '법통과', '불의에', '항거한', '4·19민주이념을', '계승하고,',
       '조국의', '민주개혁과', '평화적', '통일의', '사명에', '입각하여', '정의·인도와', '동포애로써',
       '민족의', '단결을', '공고히', '하고,', '모든', '사회적', '폐습과', '불의를', '타파하며,',
       '자율과', '조화를', '바탕으로', '자유민주적', '기본질서를', '더욱', '확고히', '하여',
       '정치·경제·사회·문화의', '모든', '영역에', '있어서', '각인의', '기회를', '균등히', '하고,',
       '능력을', '최고도로', '발휘하게', '하며,', '자유와', '권리에', '따르는', '책임과', '의무를',
       '완수하게', '하여,', '안으로는', '국민생활의', '균등한', '향상을', '기하고', '밖으로는',
       '항구적인', '세계평화와', '인류공영에', '이바지함으로써', '우리들과', '우리들의', '자손의', '안전과',
       '자유와', '행복을', '영원히', '확보할', '것을', '다짐하면서', '1948년', '7월', '12일에',
       '제정되고', '8차에', '걸쳐', '개정된', '헌법을', '이제', '국회의', '의결을', '거쳐',
       '국민투표에', '의하여', '개정한다.', '제1장', '총강', '제1조', '①', '대한민국은',
       '민주공화국이다.'], dtype='<U32')

### get_tfidf_from_konlpy()

In [9]:
documents, vectorizer, tfidf = get_tfidf_from_konlpy()

In [10]:
documents

array(['1809896.txt', '1809897.txt', '1809895.txt', '1809894.txt',
       '1809890.txt', '1809891.txt', '1809893.txt', '1809892.txt',
       '1809899.txt', '1809898.txt'], dtype='<U11')

In [11]:
vectorizer

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=<bound method Kkma.morphs of <konlpy.tag._kkma.Kkma object at 0x1a24417cf8>>,
        use_idf=True, vocabulary=None)

In [12]:
lexicon_list = np.array(vectorizer.get_feature_names())
lexicon_list[500:1000]

array(['대하', '대학', '더', '더라', '더라도', '데', '델', '도', '도록', '도모', '독점',
       '돌보', '동', '동반자', '동안', '동원', '동의', '동참', '되', '두', '둘째', '듣', '들',
       '등', '등록', '등하교', '디자인', '따', '따뜻', '따라', '따르', '때', '때문', '또',
       '또는', '또한', '라', '라고', '락', '란하', '람ㆍ', '략', '러하', '려', '려는', '력',
       '련이', '령', '로', '로서', '로써', '록', '롭', '류', '른', '를', '리', '리트',
       '린', '립하', '마', '마련', '마찰', '만', '만들', '많', '말하', '매년', '매매', '매우',
       '며', '면', '면서', '면역', '명', '명백', '명시', '명이', '명하', '명확히', '모',
       '모델', '모든', '목', '목적', '못', '무', '무부', '무원', '무정부', '무회', '문',
       '문의', '문제', '문제점', '문학', '문화', '물론', '물자', '므로', '미', '미만', '미비점',
       '미치', '민', '민간', '민사', '및', '바', '바레인', '바탕', '박', '박은수', '밖', '반',
       '반려', '반영', '받', '발', '발생', '발의', '발전', '방과', '방문', '방법', '방산',
       '방안', '방위', '방지', '방한', '배', '배경', '배상', '배상법', '배숙', '배타적', '백',
       '백만', '백성', '백재', '번역본', '번호', '벌', '벌금', '벌칙', '범', '범위', '범죄',
       '법', '법령', '법률', '법률안', '법리', '법무부', '법안', '법원', '법의

In [13]:
# lexicon dictionary
lexicon_dict = vectorizer.vocabulary_

In [14]:
# lexicon list에서 dictionary 만들기 (ndarray)
lexicon_dict = np.array([[token, idx] for (idx, token) in enumerate(lexicon_list)])
lexicon_dict.shape

(1486, 2)

In [15]:
df = pd.DataFrame(tfidf.toarray(), columns=lexicon_list, index=documents)
df.shape

(10, 1486)

In [16]:
df.T[500:520]

1809896.txt  1809897.txt  1809895.txt  1809894.txt  1809890.txt  \
대하      0.020685     0.023462     0.015092     0.046666     0.003677   
대학      0.000000     0.000000     0.000000     0.063109     0.000000   
더       0.000000     0.000000     0.000000     0.000000     0.032877   
더라      0.000000     0.000000     0.000000     0.000000     0.006575   
더라도     0.000000     0.000000     0.000000     0.000000     0.006575   
데       0.000000     0.000000     0.000000     0.000000     0.000000   
델       0.000000     0.000000     0.000000     0.000000     0.005905   
도       0.003776     0.015419     0.016530     0.000000     0.016108   
도록      0.012514     0.000000     0.032869     0.016939     0.000000   
도모      0.007927     0.000000     0.000000     0.000000     0.000000   
독점      0.009325     0.000000     0.000000     0.000000     0.000000   
돌보      0.000000     0.000000     0.000000     0.000000     0.007396   
동       0.000000     0.000000     0.000000     0.000000     0.013151   
동반자     0.000000     0.012692     0.000000     0.000000     0.000000   
동안      0.000000     0.000000     0.000000     0.000000     0.000000   
동원      0.009325     0.000000     0.000000     0.000000     0.000000   
동의      0.000000     0.118682     0.000000     0.000000     0.000000   
동참      0.000000     0.000000     0.000000     0.000000     0.000000   
되       0.056884     0.014077     0.030183     0.011666     0.047795   
두       0.000000     0.000000     0.000000     0.000000     0.007396   

     1809891.txt  1809893.txt  1809892.txt  1809899.txt  1809898.txt  
대하      0.003714     0.003972     0.002777     0.001291     0.009378  
대학      0.000000     0.000000     0.000000     0.000000     0.000000  
더       0.033208     0.035516     0.024835     0.000000     0.000000  
더라      0.006642     0.007103     0.004967     0.000000     0.000000  
더라도     0.006642     0.007103     0.004967     0.000000     0.000000  
데       0.000000     0.010742     0.000000     0.000000     0.000000  
델       0.005965     0.006379     0.004461     0.000000     0.030123  
도       0.016270     0.017401     0.009126     0.004243     0.010271  
도록      0.000000     0.000000     0.004033     0.005625     0.006808  
도모      0.000000     0.009132     0.000000     0.000000     0.000000  
독점      0.000000     0.000000     0.000000     0.000000     0.000000  
돌보      0.007470     0.015979     0.000000     0.000000     0.000000  
동       0.013283     0.014206     0.009934     0.000000     0.000000  
동반자     0.000000     0.000000     0.000000     0.000000     0.000000  
동안      0.000000     0.000000     0.000000     0.003493     0.000000  
동원      0.000000     0.000000     0.000000     0.000000     0.000000  
동의      0.000000     0.000000     0.000000     0.000000     0.140150  
동참      0.000000     0.000000     0.000000     0.000000     0.025364  
되       0.048277     0.051631     0.044436     0.029701     0.023444  
두       0.007470     0.000000     0.000000     0.002598     0.000000

In [17]:
okt_doc, okt_vec, okt_tfidf = get_tfidf_from_konlpy(k_morpheme=Okt)

In [18]:
okt_doc

array(['1809896.txt', '1809897.txt', '1809895.txt', '1809894.txt',
       '1809890.txt', '1809891.txt', '1809893.txt', '1809892.txt',
       '1809899.txt', '1809898.txt'], dtype='<U11')

In [19]:
okt_vec

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=<bound method Okt.morphs of <konlpy.tag._okt.Okt object at 0x1ab9a8eda0>>,
        use_idf=True, vocabulary=None)

In [20]:
okt_lexicon_list = np.array(okt_vec.get_feature_names())
okt_lexicon_list[500:1000]

array(['근본', '금', '금고', '금액', '금지', '급', '급속히', '급여', '급증', '급할', '기',
       '기간', '기관', '기구', '기능', '기대', '기록', '기본', '기업체', '기여', '기자', '기준',
       '기타', '기회', '기획', '기획재정부', '긴급', '긴급히', '긴밀한', '김', '김금래', '김성곤',
       '김을동', '김재윤', '김정훈', '김춘진', '김태원', '김학송', '김효석', '까', '까지', '까지로',
       '까지를', '까지에', '까지와', '까지의', '까지임', '나', '나성린', '나아가', '나은', '나이',
       '나타나는', '난민', '날', '남녀', '내', '내용', '내지', '널리', '녀', '노', '노력',
       '노출', '논의', '높이', '누락', '느', '는', '늘어날', '능력', '니', '다', '다고',
       '다만', '다시', '다양한', '다음', '단계', '단서', '단순한', '단위', '단정', '단체', '단축',
       '달', '달성', '담', '당사자', '당시', '당하는', '당해', '대', '대가', '대령', '대방',
       '대비', '대상', '대상자', '대신', '대응', '대입', '대책', '대체', '대칭', '대통령',
       '대통령령', '대표', '대하', '대학', '대한', '대해', '더', '델', '도', '도모', '도지사',
       '독점', '돌보기', '돌보는', '돌보는데', '동', '동반', '동안', '동원', '동의', '동참', '되',
       '되고', '되나', '되는', '되도록', '되어', '되어야', '되어있고', '되었을', '되었음', '되지',
       '된', '된다', '될', '됨', '됨에', '두', '두어야', '둘째', '듣도록'

In [21]:
okt_df = pd.DataFrame(okt_tfidf.toarray(), columns=okt_lexicon_list, index=okt_doc)
okt_df.shape

(10, 1669)

In [22]:
okt_df.T[500:520]

1809896.txt  1809897.txt  1809895.txt  1809894.txt  1809890.txt  \
근본      0.005375     0.000000     0.000000          0.0     0.000000   
금       0.000000     0.000000     0.000000          0.0     0.000000   
금고      0.000000     0.000000     0.000000          0.0     0.000000   
금액      0.000000     0.000000     0.047136          0.0     0.000000   
금지      0.000000     0.000000     0.000000          0.0     0.000000   
급       0.000000     0.000000     0.000000          0.0     0.036483   
급속히     0.000000     0.011276     0.000000          0.0     0.000000   
급여      0.000000     0.000000     0.000000          0.0     0.065000   
급증      0.000000     0.000000     0.000000          0.0     0.000000   
급할      0.000000     0.000000     0.000000          0.0     0.008125   
기       0.000000     0.000000     0.000000          0.0     0.007297   
기간      0.026248     0.015016     0.000000          0.0     0.005455   
기관      0.045696     0.000000     0.000000          0.0     0.000000   
기구      0.000000     0.000000     0.000000          0.0     0.000000   
기능      0.010751     0.000000     0.000000          0.0     0.000000   
기대      0.000000     0.011276     0.000000          0.0     0.000000   
기록      0.000000     0.000000     0.000000          0.0     0.000000   
기본      0.007996     0.008386     0.000000          0.0     0.000000   
기업체     0.000000     0.000000     0.000000          0.0     0.008125   
기여      0.000000     0.000000     0.000000          0.0     0.000000   

     1809891.txt  1809893.txt  1809892.txt  1809899.txt  1809898.txt  
근본      0.000000     0.000000     0.000000     0.000000     0.000000  
금       0.000000     0.000000     0.000000     0.005434     0.000000  
금고      0.000000     0.000000     0.000000     0.021736     0.000000  
금액      0.000000     0.000000     0.000000     0.000000     0.000000  
금지      0.000000     0.000000     0.000000     0.010868     0.000000  
급       0.036988     0.036181     0.031883     0.000000     0.014334  
급속히     0.000000     0.000000     0.000000     0.000000     0.000000  
급여      0.065899     0.064461     0.056804     0.000000     0.000000  
급증      0.000000     0.000000     0.000000     0.000000     0.012069  
급할      0.008237     0.008058     0.007100     0.000000     0.000000  
기       0.007398     0.007236     0.006377     0.003227     0.000000  
기간      0.005530     0.005409     0.009534     0.004824     0.032146  
기관      0.000000     0.000000     0.000000     0.000000     0.010260  
기구      0.000000     0.000000     0.000000     0.000000     0.012069  
기능      0.000000     0.000000     0.000000     0.000000     0.000000  
기대      0.000000     0.000000     0.000000     0.000000     0.000000  
기록      0.000000     0.000000     0.000000     0.027170     0.000000  
기본      0.000000     0.000000     0.000000     0.000000     0.008976  
기업체     0.008237     0.008058     0.007100     0.000000     0.000000  
기여      0.000000     0.010359     0.000000     0.000000     0.010260

### get_tfidf_from_nltk()

In [33]:
nltk_doc, nltk_vec, nltk_tfidf = get_tfidf_from_nltk(corpus=brown, e_tokenize=word_tokenize)
#nltk_doc, nltk_vec, nltk_tfidf = get_tfidf_from_nltk()

In [38]:
len(nltk_doc)

500

In [35]:
nltk_vec

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words='english', strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=<function word_tokenize at 0x1a226199d8>, use_idf=True,
        vocabulary=None)

In [36]:
nltk_tfidf.toarray().shape

(500, 62877)

In [47]:
nltk_pos_tag = np.array(nltk_vec.get_feature_names())
nltk_pos_tag.shape

(62877,)

In [53]:
nltk_pos_tag[10000:10100]

array(['caleb/np', 'calenda/np', 'calendar/nn', 'calendars/nns',
       'calendars/nns-hl', "calf's-foot/nn", 'calf/nn', 'calf/nn-tl',
       'calfskin/nn', "calhoun's/np", 'calhoun/np', 'caliber/nn',
       'calibers/nns', 'calibrated/vbn', 'calibrating/vbg',
       'calibration/nn', 'calibrations/nns', 'calibre/nn',
       'caliche-topped/jj', 'calico/nn', 'calif./np', 'calif./np-hl',
       "california's/np", 'california/np', 'california/np-tl',
       'californians/nps', 'caligula/np', 'calimala/fw-nn-tl',
       'calinda/nn', 'caliper/nn', 'calipers/nns', 'caliphs/nns',
       'calisthenics/nns', 'call-backs/nns', 'call/nn', 'call/nn-hl',
       'call/nn-tl', 'call/vb', 'callable/jj', 'callan/np', 'callas/np',
       'called/vbd', 'called/vbn', 'caller/nn', 'callers/nns',
       'calligraphers/nns', 'calligraphy/nn', "callin'/vbg", 'calling/nn',
       'calling/vbg', 'callous/jj', 'calloused/vbn', 'callously/rb',
       'callousness/nn', 'calls/nil', 'calls/nns', 'calls/vbz',
    

In [54]:
nltk_lexicon_list = np.array([tag.split("/")[0] for tag in nltk_pos_tag])
nltk_lexicon_list[10000:10100]

array(['caleb', 'calenda', 'calendar', 'calendars', 'calendars',
       "calf's-foot", 'calf', 'calf', 'calfskin', "calhoun's", 'calhoun',
       'caliber', 'calibers', 'calibrated', 'calibrating', 'calibration',
       'calibrations', 'calibre', 'caliche-topped', 'calico', 'calif.',
       'calif.', "california's", 'california', 'california',
       'californians', 'caligula', 'calimala', 'calinda', 'caliper',
       'calipers', 'caliphs', 'calisthenics', 'call-backs', 'call',
       'call', 'call', 'call', 'callable', 'callan', 'callas', 'called',
       'called', 'caller', 'callers', 'calligraphers', 'calligraphy',
       "callin'", 'calling', 'calling', 'callous', 'calloused',
       'callously', 'callousness', 'calls', 'calls', 'calls', 'calls',
       'calluses', 'calm', 'calm', 'calm', 'calmed', 'calmed', 'calmer',
       'calmer', 'calmest', 'calming', 'calmly', 'calmness', 'caloric',
       'calorie-heavy', 'calorie', 'calories', 'calorimeter',
       'calorimetric', "caltech'

In [55]:
nltk_df = pd.DataFrame(nltk_tfidf.toarray(), columns=nltk_lexicon_list, index=nltk_doc)
nltk_df.shape

(500, 62877)

In [71]:
df_new = nltk_df["ca01":"ca10"].T
df_new[df_new["ca01"] >0][500:520]

ca01      ca02      ca03      ca04      ca05  \
miller                0.030602  0.000000  0.000000  0.000000  0.000000   
million               0.034157  0.019440  0.062336  0.000000  0.000000   
modernizing           0.014350  0.000000  0.000000  0.000000  0.000000   
monday                0.044361  0.008416  0.000000  0.000000  0.000000   
money                 0.010540  0.009998  0.005343  0.000000  0.000000   
more                  0.008817  0.016727  0.008939  0.013339  0.022085   
most                  0.003494  0.003315  0.003543  0.007930  0.003751   
mrs.                  0.006079  0.000000  0.000000  0.000000  0.000000   
multi-million-dollar  0.014350  0.000000  0.000000  0.000000  0.000000   
must                  0.009641  0.003048  0.000000  0.007293  0.013800   
names                 0.007527  0.000000  0.000000  0.000000  0.008081   
near                  0.010147  0.000000  0.000000  0.000000  0.000000   
nevertheless          0.007172  0.000000  0.007271  0.008138  0.000000   
new                   0.019282  0.003048  0.013033  0.018233  0.003450   
newly                 0.009677  0.000000  0.000000  0.000000  0.000000   
next                  0.004535  0.004302  0.004598  0.000000  0.009736   
night                 0.018934  0.000000  0.004799  0.000000  0.010163   
no                    0.007683  0.002429  0.007790  0.020342  0.005499   
no                    0.005902  0.000000  0.000000  0.000000  0.006335   
none                  0.012442  0.000000  0.006307  0.000000  0.000000   

                          ca06      ca07      ca08      ca09      ca10  
miller                0.000000  0.000000  0.000000  0.000000  0.000000  
million               0.020443  0.000000  0.037836  0.000000  0.013771  
modernizing           0.000000  0.000000  0.000000  0.000000  0.000000  
monday                0.026549  0.009197  0.000000  0.009264  0.062596  
money                 0.000000  0.000000  0.005837  0.000000  0.000000  
more                  0.002932  0.015234  0.006511  0.012275  0.008887  
most                  0.000000  0.003622  0.019353  0.000000  0.000000  
mrs.                  0.018190  0.000000  0.000000  0.006347  0.018380  
multi-million-dollar  0.000000  0.000000  0.000000  0.000000  0.000000  
must                  0.009617  0.000000  0.003560  0.003356  0.016196  
names                 0.000000  0.000000  0.000000  0.000000  0.000000  
near                  0.000000  0.000000  0.000000  0.000000  0.000000  
nevertheless          0.000000  0.000000  0.000000  0.000000  0.000000  
new                   0.009617  0.009995  0.010680  0.010067  0.022674  
newly                 0.000000  0.000000  0.000000  0.000000  0.000000  
next                  0.000000  0.000000  0.005023  0.000000  0.013712  
night                 0.014165  0.004907  0.000000  0.004942  0.028625  
no                    0.007664  0.010620  0.005674  0.013371  0.010325  
no                    0.000000  0.000000  0.006537  0.000000  0.000000  
none                  0.000000  0.000000  0.006891  0.000000  0.006270

### Extend Lexicon

## inverted index with tf

In [24]:
collection = [
    ("Document1", "This is a sample"),
    ("Document2", "This is another sample"),
    ("Document3", "This is not sample"),
    ("Document4", "a not"),
    ("Document5", "not"),
]

In [41]:
extended_collection = []
for filename, content in collection:
    splited_content = []
    for token in content.split():
        splited_content.append(token)
    extended_collection.append((filename, splited_content))
extended_collection

[('Document1', ['This', 'is', 'a', 'sample']),
 ('Document2', ['This', 'is', 'another', 'sample']),
 ('Document3', ['This', 'is', 'not', 'sample']),
 ('Document4', ['a', 'not']),
 ('Document5', ['not'])]

In [42]:
global_lexicon, global_posting, global_document, dtm = inverted_index_with_tf(extended_collection)
print(global_lexicon)
print(global_document)
print(global_posting)

{'This': 8, 'is': 9, 'a': 12, 'sample': 11, 'another': 6, 'not': 14}
['Document1', 'Document2', 'Document3', 'Document4', 'Document5']
[[0, 0, 1.0, -1], [1, 0, 1.0, -1], [2, 0, 1.0, -1], [3, 0, 1.0, -1], [0, 1, 1.0, 0], [1, 1, 1.0, 1], [4, 1, 1.0, -1], [3, 1, 1.0, 3], [0, 2, 1.0, 4], [1, 2, 1.0, 5], [5, 2, 1.0, -1], [3, 2, 1.0, 7], [2, 3, 1.0, 2], [5, 3, 1.0, 10], [5, 4, 1.0, 13]]


In [43]:
for index_term, posting_idx in global_lexicon.items():
    # index_term:단어, posting_idx:위치
    print(index_term)
    
    while True:    # Posting Nexting: -1
        if posting_idx == -1:
            break
            
        posting_data = global_posting[posting_idx]
        print("    {0}    /    TF:{1}    /    Next:{2}".format(global_document[posting_data[1]], posting_data[2], posting_data[3]))
        posting_idx = posting_data[3]

This
    Document3    /    TF:1.0    /    Next:4
    Document2    /    TF:1.0    /    Next:0
    Document1    /    TF:1.0    /    Next:-1
is
    Document3    /    TF:1.0    /    Next:5
    Document2    /    TF:1.0    /    Next:1
    Document1    /    TF:1.0    /    Next:-1
a
    Document4    /    TF:1.0    /    Next:2
    Document1    /    TF:1.0    /    Next:-1
sample
    Document3    /    TF:1.0    /    Next:7
    Document2    /    TF:1.0    /    Next:3
    Document1    /    TF:1.0    /    Next:-1
another
    Document2    /    TF:1.0    /    Next:-1
not
    Document5    /    TF:1.0    /    Next:13
    Document4    /    TF:1.0    /    Next:10
    Document3    /    TF:1.0    /    Next:-1


## dtm-tdm-twm

In [44]:
dtm

defaultdict(<function functions.info_retrieval.inverted_index_with_tf.<locals>.<lambda>()>,
            {'Document1': defaultdict(int,
                         {'This': 1, 'is': 1, 'a': 1, 'sample': 1}),
             'Document2': defaultdict(int,
                         {'This': 1, 'is': 1, 'another': 1, 'sample': 1}),
             'Document3': defaultdict(int,
                         {'This': 1, 'is': 1, 'not': 1, 'sample': 1}),
             'Document4': defaultdict(int, {'a': 1, 'not': 1}),
             'Document5': defaultdict(int, {'not': 1})})

In [45]:
tdm = get_tdm_from_dtm(dtm)

In [46]:
tdm

defaultdict(<function functions.info_retrieval.get_tdm_from_dtm.<locals>.<lambda>()>,
            {'This': defaultdict(int,
                         {'Document1': 1, 'Document2': 1, 'Document3': 1}),
             'is': defaultdict(int,
                         {'Document1': 1, 'Document2': 1, 'Document3': 1}),
             'a': defaultdict(int, {'Document1': 1, 'Document4': 1}),
             'sample': defaultdict(int,
                         {'Document1': 1, 'Document2': 1, 'Document3': 1}),
             'another': defaultdict(int, {'Document2': 1}),
             'not': defaultdict(int,
                         {'Document3': 1, 'Document4': 1, 'Document5': 1})})

In [47]:
twm, dvw = tdm2twm(tdm, global_document)
twm

defaultdict(<function functions.info_retrieval.tdm2twm.<locals>.<lambda>()>,
            {'This': defaultdict(float,
                         {'Document1': 0.3010299956639812,
                          'Document2': 0.3010299956639812,
                          'Document3': 0.3010299956639812}),
             'is': defaultdict(float,
                         {'Document1': 0.3010299956639812,
                          'Document2': 0.3010299956639812,
                          'Document3': 0.3010299956639812}),
             'a': defaultdict(float,
                         {'Document1': 0.47712125471966244,
                          'Document4': 0.47712125471966244}),
             'sample': defaultdict(float,
                         {'Document1': 0.3010299956639812,
                          'Document2': 0.3010299956639812,
                          'Document3': 0.3010299956639812}),
             'another': defaultdict(float, {'Document2': 0.7781512503836436}),
             'not': defaultd

In [48]:
dvw

defaultdict(<function functions.info_retrieval.tdm2twm.<locals>.<lambda>()>,
            {'Document1': defaultdict(float,
                         {'This': 0.09061905828945654,
                          'is': 0.09061905828945654,
                          'a': 0.227644691705265,
                          'sample': 0.09061905828945654}),
             'Document2': defaultdict(float,
                         {'This': 0.09061905828945654,
                          'is': 0.09061905828945654,
                          'sample': 0.09061905828945654,
                          'another': 0.6055193684736281}),
             'Document3': defaultdict(float,
                         {'This': 0.09061905828945654,
                          'is': 0.09061905828945654,
                          'sample': 0.09061905828945654,
                          'not': 0.09061905828945654}),
             'Document4': defaultdict(float,
                         {'a': 0.227644691705265, 'not': 0.09061905828945654}),
 

## evaluate idf

In [49]:
global_lexicon_idf, global_document_weight = evaluate_idf(global_lexicon, global_posting, global_document)

In [50]:
global_lexicon_idf

{'This': 0.3010299956639812,
 'is': 0.3010299956639812,
 'a': 0.47712125471966244,
 'sample': 0.3010299956639812,
 'another': 0.7781512503836436,
 'not': 0.3010299956639812}

In [51]:
global_document_weight

{'Document3': 0.3624762331578262,
 'Document2': 0.8773765433419978,
 'Document1': 0.49950186657363466,
 'Document4': 0.3182637499947215,
 'Document5': 0.09061905828945654}

## numpy를 활용한 info_retrieval.py 성능 개선

In [4]:
import numpy as np
from functions import info_retrieval as ir

### tf, idf

In [5]:
a = [1, 2, 3, 4, 5, -1]
a

[1, 2, 3, 4, 5, -1]

In [6]:
arr = np.array(a)
arr

array([ 1,  2,  3,  4,  5, -1])

In [7]:
ir.raw_tf(arr)

array([1, 2, 3, 4, 5, 0])

In [8]:
ir.norm_tf(arr, len(arr))

array([0.16666667, 0.33333333, 0.5       , 0.66666667, 0.83333333,
       0.        ])

In [9]:
n = 10

In [10]:
ir.log_tf(arr)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.        ])

In [11]:
ir.log_tf(n)

1.0

In [12]:
ir.max_tf(arr, max(arr))

array([0.6, 0.7, 0.8, 0.9, 1. , 0.5])

In [13]:
df = np.array([1, 2, 10, 9, 6, 5, 0, -1])

In [14]:
ir.raw_idf(df, n)

array([1.        , 0.69897   , 0.        , 0.04575749, 0.22184875,
       0.30103   , 0.        , 0.        ])

In [15]:
ir.smoothig_idf(df, n)

array([1.04139269, 0.74036269, 0.04139269, 0.08715018, 0.26324143,
       0.34242268, 0.        , 0.        ])

In [16]:
ir.probability_idf(df, n)

array([ 0.95424251,  0.60205999,  0.        , -0.95424251, -0.17609126,
        0.        ,  0.        ,  0.        ])

https://en.wikipedia.org/wiki/Tf–idf

- query_weight 재구현 (아래 document weight와 query weight 관계 참조)

![TF_IDF_weight](../images/TF_IDF_weight.png)

### collection, clean_collection

In [5]:
collection = [
    ("Document1", "This is a sample!!!"),
    ("Document2", "This is another sample???"),
    ("Document3", "This is not sample>>>"),
    ("Document4", "is a not..."),
    ("Document5", "a not"),
]

In [6]:
cleaned_collection = clean_collection(collection)

In [7]:
cleaned_collection

[('Document1', 'This is a sample '),
 ('Document2', 'This is another sample '),
 ('Document3', 'This is not sample '),
 ('Document4', 'is a not '),
 ('Document5', 'a not')]

In [8]:
from functions.naver import NewsScraping

In [9]:
news = NewsScraping()

In [10]:
filenames = news.get_filenames(default_path="../naver_news", all_folder=True)
def getContent(file):
    with open(file, encoding="utf-8") as f:
        content = f.read()
    
    return content

collection = []   # tuple(filename, content)들의 list

for filename in filenames:
    collection.append((filename.split("/")[-1], getContent(filename)))

In [11]:
collection[:3]

[('00-01-0010682284.txt',
  '\n\n\n\n\n\n\n [앵커]불법 병역 면제, 한국 사회의 고질적인 문제 중 하나가  아닐까 싶습니다. 이번엔, 고의로 청각을  일시 마비시켜 병역을  면제받은 전직 국가대표  사이클 선수와  브로커 등이 적발됐습니다.박민철 기자의 보도입니다. [리포트] 4년 전 국가대표 사이클 선수 A씨는 병역 면제 판정을 받았습니다. 청력에 심각한 문제가 있다는 진단 때문이었지만 가짜였습니다. 밀폐된 차 안에서 2시간 가량 응원용 나팔과 자전거 경적을 사용해 일시적으로 청각을 마비시켜 장애 진단서를 발급 받은 겁니다. 같은 수법으로 병역 면제를 받았던 브로커 32살 이 모 씨가 천5백만 원을 받고 이런 수법을 알려줬습니다.이들은 병역을 면제받기 위해 이런 도구를 이용해 소음을 유발시켜 고의로 청력을 떨어뜨렸습니다. 구독자 100만 명을 넘긴 인터넷 게임방송 BJ도 5천만 원을 주고 수법을 배워 범행을 시도했습니다. 병무청은 2011년부터 7년동안 이런 수법으로 병역을 기피한 혐의 등으로 브로커 이 씨를 구속하고 7명을 불구속 입건했습니다. 최근 7년간 청각장애로 군 면제를 받은 천5백 명에 대한 자료도 들여다볼 예정입니다. [김태화/병무청 차장 : "중앙 신체검사소의 정밀 검사를 강화해 일시적으로 청력을 마비시켰는지 여부를 확인하는 등 검사 시스템을 개선하기로 했습니다."] 지난 2012년부터 2018년까지 신검을 통해 병역 면제를 받은 사람은 6천9백58명. 같은 기간 병역법 위반 혐의로 적발된 피의자는 326명입니다. 체중을 속이는 경우가 97건으로 가장 많았고, 정신질환 위장과 고의 문신, 안과질환 위장 등이 뒤를 이었습니다. 여기에 청각 장애 위장이라는 신종 수법까지 발견된만큼, 병무청은 신체검사 전반을 재점검할 계획입니다. KBS 뉴스 박민철입니다.  박민철 기자 (mcpark@kbs.co.kr)▶ [만세 지도] 우리 동네 3.1운동 현장은?▶ 네이버 채널 KBS뉴스 구독! 시원하게 털어드립니다▶ ‘TV보다

In [12]:
cleaned_collection = clean_collection(collection)

In [13]:
cleaned_collection[:3]

[('00-01-0010682284.txt',
  '  앵커 불법 병역 면제  한국 사회의 고질적인 문제 중 하나가 아닐까 싶습니다  이번엔  고의로 청각을 일시 마비시켜 병역을 면제받은 전직 국가대표 사이클 선수와 브로커 등이 적발됐습니다 박민철 기자의 보도입니다   리포트  4년 전 국가대표 사이클 선수 A씨는 병역 면제 판정을 받았습니다  청력에 심각한 문제가 있다는 진단 때문이었지만 가짜였습니다  밀폐된 차 안에서 2시간 가량 응원용 나팔과 자전거 경적을 사용해 일시적으로 청각을 마비시켜 장애 진단서를 발급 받은 겁니다  같은 수법으로 병역 면제를 받았던 브로커 32살 이 모 씨가 천5백만 원을 받고 이런 수법을 알려줬습니다 이들은 병역을 면제받기 위해 이런 도구를 이용해 소음을 유발시켜 고의로 청력을 떨어뜨렸습니다  구독자 100만 명을 넘긴 인터넷 게임방송 BJ도 5천만 원을 주고 수법을 배워 범행을 시도했습니다  병무청은 2011년부터 7년동안 이런 수법으로 병역을 기피한 혐의 등으로 브로커 이 씨를 구속하고 7명을 불구속 입건했습니다  최근 7년간 청각장애로 군 면제를 받은 천5백 명에 대한 자료도 들여다볼 예정입니다   김태화 병무청 차장    중앙 신체검사소의 정밀 검사를 강화해 일시적으로 청력을 마비시켰는지 여부를 확인하는 등 검사 시스템을 개선하기로 했습니다 지난 2012년부터 2018년까지 신검을 통해 병역 면제를 받은 사람은 6천9백58명  같은 기간 병역법 위반 혐의로 적발된 피의자는 326명입니다  체중을 속이는 경우가 97건으로 가장 많았고  정신질환 위장과 고의 문신  안과질환 위장 등이 뒤를 이었습니다  여기에 청각 장애 위장이라는 신종 수법까지 발견된만큼  병무청은 신체검사 전반을 재점검할 계획입니다  KBS 뉴스 박민철입니다  박민철 기자       만세 지도  우리 동네  1운동 현장은   네이버 채널 KBS뉴스 구독  시원하게 털어드립니다   TV보다   당신의 진짜 뉴스  케이야  '),
 ('00-02-0000205

### tf-idf ...

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]

In [4]:
vectorizer = TfidfVectorizer()

In [5]:
X = vectorizer.fit_transform(corpus)

In [6]:
print(vectorizer.get_feature_names())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


In [7]:
print(X.shape)

(4, 9)


In [8]:
X.toarray()

array([[0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.        , 0.38408524, 0.        , 0.38408524],
       [0.        , 0.6876236 , 0.        , 0.28108867, 0.        ,
        0.53864762, 0.28108867, 0.        , 0.28108867],
       [0.51184851, 0.        , 0.        , 0.26710379, 0.51184851,
        0.        , 0.26710379, 0.51184851, 0.26710379],
       [0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.        , 0.38408524, 0.        , 0.38408524]])

In [9]:
vectorizer.vocabulary_

{'this': 8,
 'is': 3,
 'the': 6,
 'first': 2,
 'document': 1,
 'second': 5,
 'and': 0,
 'third': 7,
 'one': 4}